# -*- coding: utf-8 -*-
"""git.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eh0qJdzvOlvLe6XWv5LVRBdd2UvZ82Xz
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
X = np.array([1, 2, 3, 4, 5, 6]).reshape(-1, 1)
y = np.array([10, 20, 30, 45, 60, 85])
lin_reg = LinearRegression()
lin_reg.fit(X, y)
poly = PolynomialFeatures(degree=2)
X_poly = poly.fit_transform(X)
poly_reg = LinearRegression()
poly_reg.fit(X_poly, y)
plt.scatter(X, y, color="red", label="Actual Data")
plt.plot(X, lin_reg.predict(X), color="blue", label="Linear Regression")
plt.plot(X, poly_reg.predict(X_poly), color="green", label="Polynomial Regression")
plt.xlabel("Hours Studied")
plt.ylabel("Marks Scored")
plt.legend()
plt.show()